/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CadetRouteImport } from './routes/cadet'
import { Route as CadetDatabaseRouteImport } from './routes/cadet-database'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as ApiV1ActivitiesRouteImport } from './routes/api/v1/activities'
import { Route as ApiV1AiChatRouteImport } from './routes/api/v1/ai-chat'
import { Route as ApiV1AnnualPlansRouteImport } from './routes/api/v1/annual-plans'
import { Route as ApiV1AuditRouteImport } from './routes/api/v1/audit'
import { Route as ApiV1CadetsRouteImport } from './routes/api/v1/cadets'
import { Route as ApiV1CalendarRouteImport } from './routes/api/v1/calendar'
import { Route as ApiV1EnrollmentsRouteImport } from './routes/api/v1/enrollments'
import { Route as ApiV1ExportExcelRouteImport } from './routes/api/v1/export-excel'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1MetricsRouteImport } from './routes/api/v1/metrics'
import { Route as ApiV1NotificationsRouteImport } from './routes/api/v1/notifications'
import { Route as ApiV1PhotosRouteImport } from './routes/api/v1/photos'
import { Route as ApiV1StaffAttendanceRouteImport } from './routes/api/v1/staff-attendance'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1CadetsMeRouteImport } from './routes/api/v1/cadets/me'
import { Route as ApiV1EnrollmentsStatusRouteImport } from './routes/api/v1/enrollments.status'
import { Route as ApiV1AuthOtpRequestRouteImport } from './routes/api/v1/auth/otp.request'
import { Route as ApiV1AuthOtpVerifyRouteImport } from './routes/api/v1/auth/otp.verify'
import { Route as ApiV1EnrollmentsStatusQueryRouteImport } from './routes/api/v1/enrollments.status.$query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CadetRoute = CadetRouteImport.update({
  id: '/cadet',
  path: '/cadet',
  getParentRoute: () => rootRouteImport,
} as any)
const CadetDatabaseRoute = CadetDatabaseRouteImport.update({
  id: '/cadet-database',
  path: '/cadet-database',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ActivitiesRoute = ApiV1ActivitiesRouteImport.update({
  id: '/api/v1/activities',
  path: '/api/v1/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AiChatRoute = ApiV1AiChatRouteImport.update({
  id: '/api/v1/ai-chat',
  path: '/api/v1/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AnnualPlansRoute = ApiV1AnnualPlansRouteImport.update({
  id: '/api/v1/annual-plans',
  path: '/api/v1/annual-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuditRoute = ApiV1AuditRouteImport.update({
  id: '/api/v1/audit',
  path: '/api/v1/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CadetsRoute = ApiV1CadetsRouteImport.update({
  id: '/api/v1/cadets',
  path: '/api/v1/cadets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CalendarRoute = ApiV1CalendarRouteImport.update({
  id: '/api/v1/calendar',
  path: '/api/v1/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EnrollmentsRoute = ApiV1EnrollmentsRouteImport.update({
  id: '/api/v1/enrollments',
  path: '/api/v1/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportExcelRoute = ApiV1ExportExcelRouteImport.update({
  id: '/api/v1/export-excel',
  path: '/api/v1/export-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetricsRoute = ApiV1MetricsRouteImport.update({
  id: '/api/v1/metrics',
  path: '/api/v1/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsRoute = ApiV1NotificationsRouteImport.update({
  id: '/api/v1/notifications',
  path: '/api/v1/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PhotosRoute = ApiV1PhotosRouteImport.update({
  id: '/api/v1/photos',
  path: '/api/v1/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StaffAttendanceRoute = ApiV1StaffAttendanceRouteImport.update({
  id: '/api/v1/staff-attendance',
  path: '/api/v1/staff-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CadetsMeRoute = ApiV1CadetsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiV1CadetsRoute,
} as any)
const ApiV1EnrollmentsStatusRoute = ApiV1EnrollmentsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiV1EnrollmentsRoute,
} as any)
const ApiV1AuthOtpRequestRoute = ApiV1AuthOtpRequestRouteImport.update({
  id: '/api/v1/auth/otp/request',
  path: '/api/v1/auth/otp/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthOtpVerifyRoute = ApiV1AuthOtpVerifyRouteImport.update({
  id: '/api/v1/auth/otp/verify',
  path: '/api/v1/auth/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EnrollmentsStatusQueryRoute =
  ApiV1EnrollmentsStatusQueryRouteImport.update({
    id: '/$query',
    path: '/$query',
    getParentRoute: () => ApiV1EnrollmentsStatusRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadet': typeof CadetRoute
  '/cadet-database': typeof CadetDatabaseRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/api/v1/activities': typeof ApiV1ActivitiesRoute
  '/api/v1/ai-chat': typeof ApiV1AiChatRoute
  '/api/v1/annual-plans': typeof ApiV1AnnualPlansRoute
  '/api/v1/audit': typeof ApiV1AuditRoute
  '/api/v1/cadets': typeof ApiV1CadetsRouteWithChildren
  '/api/v1/calendar': typeof ApiV1CalendarRoute
  '/api/v1/enrollments': typeof ApiV1EnrollmentsRouteWithChildren
  '/api/v1/export-excel': typeof ApiV1ExportExcelRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/metrics': typeof ApiV1MetricsRoute
  '/api/v1/notifications': typeof ApiV1NotificationsRoute
  '/api/v1/photos': typeof ApiV1PhotosRoute
  '/api/v1/staff-attendance': typeof ApiV1StaffAttendanceRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/cadets/me': typeof ApiV1CadetsMeRoute
  '/api/v1/enrollments/status': typeof ApiV1EnrollmentsStatusRouteWithChildren
  '/api/v1/auth/otp/request': typeof ApiV1AuthOtpRequestRoute
  '/api/v1/auth/otp/verify': typeof ApiV1AuthOtpVerifyRoute
  '/api/v1/enrollments/status/$query': typeof ApiV1EnrollmentsStatusQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadet': typeof CadetRoute
  '/cadet-database': typeof CadetDatabaseRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/api/v1/activities': typeof ApiV1ActivitiesRoute
  '/api/v1/ai-chat': typeof ApiV1AiChatRoute
  '/api/v1/annual-plans': typeof ApiV1AnnualPlansRoute
  '/api/v1/audit': typeof ApiV1AuditRoute
  '/api/v1/cadets': typeof ApiV1CadetsRouteWithChildren
  '/api/v1/calendar': typeof ApiV1CalendarRoute
  '/api/v1/enrollments': typeof ApiV1EnrollmentsRouteWithChildren
  '/api/v1/export-excel': typeof ApiV1ExportExcelRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/metrics': typeof ApiV1MetricsRoute
  '/api/v1/notifications': typeof ApiV1NotificationsRoute
  '/api/v1/photos': typeof ApiV1PhotosRoute
  '/api/v1/staff-attendance': typeof ApiV1StaffAttendanceRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/cadets/me': typeof ApiV1CadetsMeRoute
  '/api/v1/enrollments/status': typeof ApiV1EnrollmentsStatusRouteWithChildren
  '/api/v1/auth/otp/request': typeof ApiV1AuthOtpRequestRoute
  '/api/v1/auth/otp/verify': typeof ApiV1AuthOtpVerifyRoute
  '/api/v1/enrollments/status/$query': typeof ApiV1EnrollmentsStatusQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadet': typeof CadetRoute
  '/cadet-database': typeof CadetDatabaseRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/api/v1/activities': typeof ApiV1ActivitiesRoute
  '/api/v1/ai-chat': typeof ApiV1AiChatRoute
  '/api/v1/annual-plans': typeof ApiV1AnnualPlansRoute
  '/api/v1/audit': typeof ApiV1AuditRoute
  '/api/v1/cadets': typeof ApiV1CadetsRouteWithChildren
  '/api/v1/calendar': typeof ApiV1CalendarRoute
  '/api/v1/enrollments': typeof ApiV1EnrollmentsRouteWithChildren
  '/api/v1/export-excel': typeof ApiV1ExportExcelRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/metrics': typeof ApiV1MetricsRoute
  '/api/v1/notifications': typeof ApiV1NotificationsRoute
  '/api/v1/photos': typeof ApiV1PhotosRoute
  '/api/v1/staff-attendance': typeof ApiV1StaffAttendanceRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/cadets/me': typeof ApiV1CadetsMeRoute
  '/api/v1/enrollments/status': typeof ApiV1EnrollmentsStatusRouteWithChildren
  '/api/v1/auth/otp/request': typeof ApiV1AuthOtpRequestRoute
  '/api/v1/auth/otp/verify': typeof ApiV1AuthOtpVerifyRoute
  '/api/v1/enrollments/status/$query': typeof ApiV1EnrollmentsStatusQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadet'
    | '/cadet-database'
    | '/enroll'
    | '/login'
    | '/notices'
    | '/api/v1/activities'
    | '/api/v1/ai-chat'
    | '/api/v1/annual-plans'
    | '/api/v1/audit'
    | '/api/v1/cadets'
    | '/api/v1/calendar'
    | '/api/v1/enrollments'
    | '/api/v1/export-excel'
    | '/api/v1/health'
    | '/api/v1/metrics'
    | '/api/v1/notifications'
    | '/api/v1/photos'
    | '/api/v1/staff-attendance'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/cadets/me'
    | '/api/v1/enrollments/status'
    | '/api/v1/auth/otp/request'
    | '/api/v1/auth/otp/verify'
    | '/api/v1/enrollments/status/$query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadet'
    | '/cadet-database'
    | '/enroll'
    | '/login'
    | '/notices'
    | '/api/v1/activities'
    | '/api/v1/ai-chat'
    | '/api/v1/annual-plans'
    | '/api/v1/audit'
    | '/api/v1/cadets'
    | '/api/v1/calendar'
    | '/api/v1/enrollments'
    | '/api/v1/export-excel'
    | '/api/v1/health'
    | '/api/v1/metrics'
    | '/api/v1/notifications'
    | '/api/v1/photos'
    | '/api/v1/staff-attendance'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/cadets/me'
    | '/api/v1/enrollments/status'
    | '/api/v1/auth/otp/request'
    | '/api/v1/auth/otp/verify'
    | '/api/v1/enrollments/status/$query'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadet'
    | '/cadet-database'
    | '/enroll'
    | '/login'
    | '/notices'
    | '/api/v1/activities'
    | '/api/v1/ai-chat'
    | '/api/v1/annual-plans'
    | '/api/v1/audit'
    | '/api/v1/cadets'
    | '/api/v1/calendar'
    | '/api/v1/enrollments'
    | '/api/v1/export-excel'
    | '/api/v1/health'
    | '/api/v1/metrics'
    | '/api/v1/notifications'
    | '/api/v1/photos'
    | '/api/v1/staff-attendance'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/cadets/me'
    | '/api/v1/enrollments/status'
    | '/api/v1/auth/otp/request'
    | '/api/v1/auth/otp/verify'
    | '/api/v1/enrollments/status/$query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadetRoute: typeof CadetRoute
  CadetDatabaseRoute: typeof CadetDatabaseRoute
  EnrollRoute: typeof EnrollRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  ApiV1ActivitiesRoute: typeof ApiV1ActivitiesRoute
  ApiV1AiChatRoute: typeof ApiV1AiChatRoute
  ApiV1AnnualPlansRoute: typeof ApiV1AnnualPlansRoute
  ApiV1AuditRoute: typeof ApiV1AuditRoute
  ApiV1CadetsRoute: typeof ApiV1CadetsRouteWithChildren
  ApiV1CalendarRoute: typeof ApiV1CalendarRoute
  ApiV1EnrollmentsRoute: typeof ApiV1EnrollmentsRouteWithChildren
  ApiV1ExportExcelRoute: typeof ApiV1ExportExcelRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1MetricsRoute: typeof ApiV1MetricsRoute
  ApiV1NotificationsRoute: typeof ApiV1NotificationsRoute
  ApiV1PhotosRoute: typeof ApiV1PhotosRoute
  ApiV1StaffAttendanceRoute: typeof ApiV1StaffAttendanceRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1AuthOtpRequestRoute: typeof ApiV1AuthOtpRequestRoute
  ApiV1AuthOtpVerifyRoute: typeof ApiV1AuthOtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadet': {
      id: '/cadet'
      path: '/cadet'
      fullPath: '/cadet'
      preLoaderRoute: typeof CadetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadet-database': {
      id: '/cadet-database'
      path: '/cadet-database'
      fullPath: '/cadet-database'
      preLoaderRoute: typeof CadetDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/activities': {
      id: '/api/v1/activities'
      path: '/api/v1/activities'
      fullPath: '/api/v1/activities'
      preLoaderRoute: typeof ApiV1ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ai-chat': {
      id: '/api/v1/ai-chat'
      path: '/api/v1/ai-chat'
      fullPath: '/api/v1/ai-chat'
      preLoaderRoute: typeof ApiV1AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/annual-plans': {
      id: '/api/v1/annual-plans'
      path: '/api/v1/annual-plans'
      fullPath: '/api/v1/annual-plans'
      preLoaderRoute: typeof ApiV1AnnualPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/audit': {
      id: '/api/v1/audit'
      path: '/api/v1/audit'
      fullPath: '/api/v1/audit'
      preLoaderRoute: typeof ApiV1AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cadets': {
      id: '/api/v1/cadets'
      path: '/api/v1/cadets'
      fullPath: '/api/v1/cadets'
      preLoaderRoute: typeof ApiV1CadetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calendar': {
      id: '/api/v1/calendar'
      path: '/api/v1/calendar'
      fullPath: '/api/v1/calendar'
      preLoaderRoute: typeof ApiV1CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/enrollments': {
      id: '/api/v1/enrollments'
      path: '/api/v1/enrollments'
      fullPath: '/api/v1/enrollments'
      preLoaderRoute: typeof ApiV1EnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export-excel': {
      id: '/api/v1/export-excel'
      path: '/api/v1/export-excel'
      fullPath: '/api/v1/export-excel'
      preLoaderRoute: typeof ApiV1ExportExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/metrics': {
      id: '/api/v1/metrics'
      path: '/api/v1/metrics'
      fullPath: '/api/v1/metrics'
      preLoaderRoute: typeof ApiV1MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications': {
      id: '/api/v1/notifications'
      path: '/api/v1/notifications'
      fullPath: '/api/v1/notifications'
      preLoaderRoute: typeof ApiV1NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/photos': {
      id: '/api/v1/photos'
      path: '/api/v1/photos'
      fullPath: '/api/v1/photos'
      preLoaderRoute: typeof ApiV1PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/staff-attendance': {
      id: '/api/v1/staff-attendance'
      path: '/api/v1/staff-attendance'
      fullPath: '/api/v1/staff-attendance'
      preLoaderRoute: typeof ApiV1StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cadets/me': {
      id: '/api/v1/cadets/me'
      path: '/me'
      fullPath: '/api/v1/cadets/me'
      preLoaderRoute: typeof ApiV1CadetsMeRouteImport
      parentRoute: typeof ApiV1CadetsRoute
    }
    '/api/v1/enrollments/status': {
      id: '/api/v1/enrollments/status'
      path: '/status'
      fullPath: '/api/v1/enrollments/status'
      preLoaderRoute: typeof ApiV1EnrollmentsStatusRouteImport
      parentRoute: typeof ApiV1EnrollmentsRoute
    }
    '/api/v1/auth/otp/request': {
      id: '/api/v1/auth/otp/request'
      path: '/api/v1/auth/otp/request'
      fullPath: '/api/v1/auth/otp/request'
      preLoaderRoute: typeof ApiV1AuthOtpRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/otp/verify': {
      id: '/api/v1/auth/otp/verify'
      path: '/api/v1/auth/otp/verify'
      fullPath: '/api/v1/auth/otp/verify'
      preLoaderRoute: typeof ApiV1AuthOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/enrollments/status/$query': {
      id: '/api/v1/enrollments/status/$query'
      path: '/$query'
      fullPath: '/api/v1/enrollments/status/$query'
      preLoaderRoute: typeof ApiV1EnrollmentsStatusQueryRouteImport
      parentRoute: typeof ApiV1EnrollmentsStatusRoute
    }
  }
}

interface ApiV1CadetsRouteChildren {
  ApiV1CadetsMeRoute: typeof ApiV1CadetsMeRoute
}

const ApiV1CadetsRouteChildren: ApiV1CadetsRouteChildren = {
  ApiV1CadetsMeRoute: ApiV1CadetsMeRoute,
}

const ApiV1CadetsRouteWithChildren = ApiV1CadetsRoute._addFileChildren(
  ApiV1CadetsRouteChildren,
)

interface ApiV1EnrollmentsStatusRouteChildren {
  ApiV1EnrollmentsStatusQueryRoute: typeof ApiV1EnrollmentsStatusQueryRoute
}

const ApiV1EnrollmentsStatusRouteChildren: ApiV1EnrollmentsStatusRouteChildren =
  {
    ApiV1EnrollmentsStatusQueryRoute: ApiV1EnrollmentsStatusQueryRoute,
  }

const ApiV1EnrollmentsStatusRouteWithChildren =
  ApiV1EnrollmentsStatusRoute._addFileChildren(
    ApiV1EnrollmentsStatusRouteChildren,
  )

interface ApiV1EnrollmentsRouteChildren {
  ApiV1EnrollmentsStatusRoute: typeof ApiV1EnrollmentsStatusRouteWithChildren
}

const ApiV1EnrollmentsRouteChildren: ApiV1EnrollmentsRouteChildren = {
  ApiV1EnrollmentsStatusRoute: ApiV1EnrollmentsStatusRouteWithChildren,
}

const ApiV1EnrollmentsRouteWithChildren =
  ApiV1EnrollmentsRoute._addFileChildren(ApiV1EnrollmentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadetRoute: CadetRoute,
  CadetDatabaseRoute: CadetDatabaseRoute,
  EnrollRoute: EnrollRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  ApiV1ActivitiesRoute: ApiV1ActivitiesRoute,
  ApiV1AiChatRoute: ApiV1AiChatRoute,
  ApiV1AnnualPlansRoute: ApiV1AnnualPlansRoute,
  ApiV1AuditRoute: ApiV1AuditRoute,
  ApiV1CadetsRoute: ApiV1CadetsRouteWithChildren,
  ApiV1CalendarRoute: ApiV1CalendarRoute,
  ApiV1EnrollmentsRoute: ApiV1EnrollmentsRouteWithChildren,
  ApiV1ExportExcelRoute: ApiV1ExportExcelRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1MetricsRoute: ApiV1MetricsRoute,
  ApiV1NotificationsRoute: ApiV1NotificationsRoute,
  ApiV1PhotosRoute: ApiV1PhotosRoute,
  ApiV1StaffAttendanceRoute: ApiV1StaffAttendanceRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1AuthOtpRequestRoute: ApiV1AuthOtpRequestRoute,
  ApiV1AuthOtpVerifyRoute: ApiV1AuthOtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
