CREATE TABLE IF NOT EXISTS public.cadets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enrollment_id text NOT NULL UNIQUE,
  batch text,
  rank text,
  full_name text,
  gender text,
  wing text,
  mobile text,
  email text,
  dob text,
  father_name text,
  mother_name text,
  nationality text,
  institute text,
  ano_name text,
  wing_type text,
  group_hq text,
  house_no text,
  building text,
  area text,
  city text,
  state text,
  pin_code text,
  nearest_railway_station text,
  identification_mark text,
  blood_group text,
  medical_complaint text,
  nok_name text,
  nok_relationship text,
  nok_contact text,
  nok_address text,
  sports_games text,
  co_curricular text,
  willing_military_training text,
  willing_serve_ncc text,
  previously_applied text,
  criminal_record text,
  sbu_id text,
  course text,
  branch text,
  semester text,
  section text,
  bank_account_number text,
  ifsc_code text,
  account_holder_name text,
  aadhaar_number text,
  stipend_received text,
  performance text,
  behaviour text,
  participation text,
  distinction text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.cadets TO service_role;

ALTER TABLE public.cadets ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS cadets_batch_idx ON public.cadets (batch);
CREATE INDEX IF NOT EXISTS cadets_name_idx ON public.cadets (lower(full_name));